import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import NavTransition from "@/components/NavTransition"; // <-- thêm

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: "--font-jetbrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jetbrainsMono.variable}>
      <body>
        {/* Navbar: blur + fade */}
        <NavTransition>
          <Header />
        </NavTransition>

        {/* Nội dung: flip 3D */}
        <PageTransition variant="flip">
          {children}
        </PageTransition>
      </body>
    </html>
  );
}
